# Disable debug logging
CONFIG_ZMK_USB_LOGGING=n

CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y
# N-key rollover
# Allows pressing more than 6 keys at the same time.
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Debounce
# Eager debounce, use 1ms on press to avoid noise spikes, use 15ms on release
# to avoid double taps (10ms also works but they still go through sometimes
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Deep sleep
# Configured at 24 hours
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=86400000

# Polling interval
# Set to 1000hz update frequency (low latency) for USB.
# Bluetooth will be limited to 125hz or maybe 133hz AFAIK.
CONFIG_USB_HID_POLL_INTERVAL_MS=1

# Bluetooth latency optimizations
# Increase transfer power and enable low-latency features.
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_CTLR_LOW_LAT=y
CONFIG_BT_CTLR_LOW_LAT_ULL=y
CONFIG_BT_CTLR_LOW_LAT_ULL_DONE=y
CONFIG_BT_TICKER_LOW_LAT=y

# Turn off RGB
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# If you accidentally unbind &studio_unlock, uncomment to disable locking and reflash to get yourself back in.
# Permanently disabling locking is not advised as that will allow any program to change your keymap at any time.
#CONFIG_ZMK_STUDIO_UNLOCK=n

# Some operating systems (currently macOS, Android) have problems with full support for consumer keycodes.
# If yours does not, comment this out in order for keycodes like C_AL_CALC to work.
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

CONFIG_BT_CTLR_PHY_2M=n
